spring:
  output:
    ansi:
      enabled: always
  application:
    name: itoken-sso
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: ${driver-class-name}
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      connection-init-sqls: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  profiles:
    include: db

server:
  port: 8771

feign:
  hystrix:
    enabled: true # 奇怪的是这个属性找不到

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.draper.itoken.sso.domain
